import fs from "fs";
import path from "path";

export class ModuleWrite {
  private builderLines: string[] = [];
  private outputPath: string;

  constructor(outputPath: string) {
    this.outputPath = outputPath;

    this.pushAutoGeneratedComment();
  }

  private pushAutoGeneratedComment() {
    this.pushComment(
      "// This file is auto-generated. Do not edit it manually."
    );
    this.pushComment("// It will be overwritten on the next build.");
  }

  pushBlankLine() {
    this.builderLines.push("");
  }

  push(text: string) {
    this.builderLines.push(text);
  }

  pushComment(comment: string) {
    this.builderLines.push(`// ${comment}`);
  }

  pushImport(importPath: string, importModules: string[]) {
    if (!importModules.length) return;

    this.builderLines.push(
      `import { ${importModules.join(", ")} } from "${importPath
        .replace("src", "@")
        .replace(".ts", "")}";`
    );
  }

  save() {
    fs.mkdirSync(path.dirname(this.outputPath), {recursive: true});
    fs.writeFileSync(this.outputPath, this.builderLines.join("\n"));
  }
}
